### ISSUE TITLE
NotVerifiedException on testnet

### ISSUE THREAD

**Issue by terry-v5** [inference-labs-inc/omron-subnet#16]
When I didn't turn on the Nginx proxy, everything worked properly on testnet.
Then I follow the guide of [DDOS Mitigation Guide](https://inference-labs.medium.com/bittensor-miner-ddos-mitigation-guide-3286c63aa2d2) , get an error:
`ERROR       |  - NotVerifiedException#9bb88c36-6374-4caf-a1da-96a0c847c28c: Not Verified with error: No SS58 formatted address or public key provided -`

The Nginx config:
`server {
	listen 8086 default_server;
	listen [::]:8086 default_server;
	server_name _;

	location / {
		include proxy_params;
		proxy_redirect off;
 		proxy_buffering off;
		proxy_pass http://127.0.0.1:18086;
	}
}`

Run the miner with pm2 cmd:
`pm2 start miner.py --name miner-18086 --interpreter python3 -- --disable_blacklist true --netuid 118 --wallet.name miner --wallet.hotkey default --subtensor.network test --axon.ip 127.0.0.1 --axon.port 18086 --axon.external_ip 34.94.73.66  --axon.external_port 8086 --no-auto-update --disable-wandb --logging.debug`

bittensor  Version: 7.3.1

**Comment by 0xean** [comment]
you need to configure nginx to pass headers

**Comment by HudsonGraeme** [comment]
As @0xean mentioned, you should be able to receive requests as expected by enabling header passthrough. Since dendrite headers include underscores, I believe this configuration line will resolve the issue:

```
underscores_in_headers on;
```

**Comment by terry-v5** [comment]
Cool! Thanks a lot!
