### ISSUE TITLE
How the circom model compiled?

### ISSUE THREAD

**Issue by qy3u** [inference-labs-inc/omron-subnet#23]
I would like to compile model_55de10 and model_9998a from the Circom source code.

I noticed that the Circom code is only located in the model_55de10 directory and is configured as follows:
```
component main {public [RATE_OF_DECAY, ..., scaling]} = Reward(256,40);
```

However, the settings.json file in model_55de10 specifies that the size parameter should be 1024. Should I change `Reward(256,40)` to `Reward(1024,40)` to properly compile model_55de10?

Additionally, are there any specific compilation arguments I should use? Currently, I am using `circom reward.circom --wasm` to generate the WASM file, but it appears that the output doesn’t match the WASM file provided in the repository. Would adding `--O2 `or other options produce a more accurate match?

Thanks!

**Comment by HudsonGraeme** [comment]
Hello, thank you for opening this issue. We will be releasing updated circuits for both 256 and 1024 models shortly, and recommend compiling for those targets afterwards. Notifications will be providing guidance in the Discord chat relating to this release.
